stages:
  - build
  - deploy

build:
  tags:
    - other
  stage: build
  image: node:14
  script:
    - npm install
    - npm run lint
    - npm run build
    - cd build && tar czfv build.tarz * && mv build.tarz ../ && cd ..
  artifacts:
    paths:
      - build.tarz

deploy:
  stage: deploy
  tags:
    - other
  image: registry.gitlab.com/riverwaysoft/rebelbee/phonedo_project/ansible-phonedo-playbooks:latest
  script:
    - cd /usr/src/playbooks && ansible-playbook -i prod deploy/phonedo/frontend/deploy_webrtc_app.yml -e "ansistrano_deploy_from=$CI_PROJECT_DIR/build.tarz"
  dependencies:
    - build
  environment:
    name: staging
  only:
    - main
  when: manual


